### ISSUE TITLE
Which version of jQuery? Only built in?

### ISSUE THREAD

**Issue by chadsterBAM** [andrew-worsfold/tailor#119] opened 2017-06-08 18:06 UTC
I'm having an issue with : 
"Cannot read property 'deleteRules' of undefined"
and 
"this.$el.imagesLoaded is not a function" on my multisite.  I figure it's because I've disabled builtin JS and compiled my own version that goes with the theme.

Thoughts?

**Comment by andrew-worsfold** [comment] 2017-06-12 06:20
Tailor uses the version of jQuery bundled with WordPress, as this is best practice.  The errors you're seeing could be caused by those changes, but I'd recommend installing Tailor in a new WordPress installation and make changes incrementally to help troubleshoot.

**Comment by andrew-worsfold** [comment] 2017-06-25 09:33
Closing as it's unclear whether this is related to your custom jQuery build.  Feel free to raise another issue if you still have trouble and are able to provide more information.

**Closed by andrew-worsfold** 2017-06-25 09:33 UTC
