### ISSUE TITLE
Error: An "el" #canvas must exist in DOM

### ISSUE THREAD

**Issue by anardil** [andrew-worsfold/tailor#5] opened 2016-07-04 08:44 UTC
Hello,

I have an error when I drag'n drop an element.
Error: An "el" #canvas must exist in DOM and TypeError: this.el is undefined

So I can't do anything. :(

Can you help me please ?
Thank u.

**Comment by andrew-worsfold** [comment] 2016-07-04 09:50
Which version of Tailor are you using?

Tailor filters the page content to add the drag and drop canvas when "tailoring" the page, which suggests that this is a plugin (or possibly theme) conflict.  Could you please try deactivating all plugins and then check to see if you get the same problem?  If you deactivate all plugins and are still having the problem, try changing to a default theme (e.g., Twenty Sixteen).

Let me know what happens and we'll go from there :)

**Comment by mikenolan** [comment] 2016-07-12 11:13
We're getting this issue with Jetpack enabled.

**Comment by andrew-worsfold** [comment] 2016-07-12 11:18
Are you using the latest version of Tailor?  Is it only Jetpack that's causing the issue? What other plugins do you have running? Any idea which Jetpack module could be causing the issue? 

I'm running Jetpack with no issues, which makes it difficult to troubleshoot from here.

**Comment by mikenolan** [comment] 2016-07-12 11:24
Yes, tried with the latest version too. We've got a whole bunch of Jetpack modules active and haven't yet had a chance to go through them to work out what's causing the issue. It seems to be just Jetpack on our site, though we use quite a few downloaded and bespoke plugins.

**Comment by mikenolan** [comment] 2016-07-12 11:27
Saying that - I see you've just pushed 1.2.7 and we've not tried that yet, just 1.2.6 earlier today.

**Comment by andrew-worsfold** [comment] 2016-07-12 11:46
1.2.7 just adds RTL support.  This is almost certainly the result of another plugin doing something with the content as that error message suggests that the canvas HTML hasn't been inserted into the page.

Most plugins shouldn't filter the content, but some do.  It's just a matter of figuring out which plugin is causing the issue.  I can then create a compatibility patch (if appropriate).

**Comment by mikenolan** [comment] 2016-07-12 12:45
So Sharing and Publicize seem to be the offenders from a quick run through (there may be others):

https://jetpack.com/support/publicize/
https://jetpack.com/support/sharing/

There may well be others too. We make fairly extensive use of Sharing but not Publicize.

**Comment by andrew-worsfold** [comment] 2016-07-12 13:18
So it works when they are both disabled?

What theme are you using?

I have Jetpack enabled with those features activated and everything's working as expected 😕 

![screen shot 2016-07-12 at 11 14 31 pm](https://cloud.githubusercontent.com/assets/5225074/16768194/a372ed90-4886-11e6-8518-dd2d9669e35c.png)

**Comment by mikenolan** [comment] 2016-07-12 13:27
We have our own theme which is a heavily modified Twenty Twelve, but I've also tested with Twenty Sixteen. We use WordPress Multisite.

**Comment by andrew-worsfold** [comment] 2016-07-12 13:33
Have you been able to get Tailor to work at all (i.e., by disabling those two Jackpack modules)?

**Comment by mikenolan** [comment] 2016-07-12 13:54
Yes, that works fine so we're okay to test before we decide whether to use for production, in which case we should be able to put more resources into working out what the problem is.

**Comment by andrew-worsfold** [comment] 2016-07-18 12:58
Thanks, Mike.  As I'm unable to reproduce this I'll close this issue out.  If you do continue to use Tailor and continue to experience the problem, please raise another issue and we'll continue investigating.

**Closed by andrew-worsfold** 2016-07-18 12:58 UTC
