### ISSUE TITLE
"Tailor this Page" never displays

### ISSUE THREAD

**Issue by pesh2000** [andrew-worsfold/tailor#26] opened 2016-08-26 00:25 UTC
I installed the plugin against a fresh install running Twenty Sixteen and I never get the button. Nothing is shown in the JS console or in PHP logs. I switched to a new Underscores theme and the results are the same.

Do I need a DOM element in my templates for Tailor to work with? Something else I am missing?

**Comment by andrew-worsfold** [comment] 2016-08-26 01:15
Absolutely not.  Tailor should just work with any theme (particularly one of the default WordPress ones). 

A few questions:
1. Is anything added to either the WordPress Admin Bar or the "actions" menu on the page list?
2. Are you trying to Tailor a page, or post?  Is editing enabled for that post type in the settings?
3. What happens if you view a page and append "?tailor=1" to the URL?

**Comment by pesh2000** [comment] 2016-08-26 01:24
1. Nothing is added to the admin bar or to the actions menu.

**Comment by andrew-worsfold** [comment] 2016-08-26 01:41
Very strange.  And it sounds like you're seeing the Settings page too..

Are you running a local server?  It'd be great to be able to check it out quickly, as to be honest have no idea what could be causing it..

Do you have another server to test on for comparisons sake?

**Comment by pesh2000** [comment] 2016-08-26 01:48
Running MAMP locally. I installed the plugin on a staging environment in a custom theme I wrote using Underscores as a starting point and it worked immediately. Looks as impressive as I've heard.

I am heading off to vacation for a week, but I will see if I can increase the logging level in my local environment and get some meaningful data for you when I get back.

**Comment by andrew-worsfold** [comment] 2016-08-26 01:57
👍  sounds good.

Interestingly I also have a MAMP environment in which it works well.  I'm very interested to learn what the root cause of this is!

**Comment by andrew-worsfold** [comment] 2016-09-12 11:15
@pesh2000 Just following up on this - I don't suppose you had any luck in figuring out what was going on here, did you?

**Comment by andrew-worsfold** [comment] 2016-09-29 07:27
@pesh2000 -

As I've been unable to reproduce this issue and given there have been a number of releases since you reported this, I will close this issue.   If you are still having trouble, please raise another issue and I'll be more than happy to help troubleshoot it further.

**Closed by andrew-worsfold** 2016-09-29 07:27 UTC

**Comment by pesh2000** [comment] 2016-10-11 14:48
Sorry for not getting back to you. I am 99% confident that the issue is in my local build environment. I can't replicate it in two different staging environments, one nginx and php7 and one apache and php5.6.
