### ISSUE TITLE
Live updates to Button do not target correct DOM node

### ISSUE THREAD

**Issue by talesg** [andrew-worsfold/tailor#50] opened 2016-10-10 12:21 UTC
If padding is defined and some value from the "General" tab is changed (such as label or link), the padding is lost (although the recorded setting still remains).

**To replicate:**

1. Add button
2. Change padding-left to 50px
3. Apply
4. Edit the button
5. Change link or label
6. Verify that the left padding was lost

Obs: using latest Tailor version in one test site only. Didn't tested in any other site.

--

Other 2 Things About Padding/Margin:

1) I think it would be much better if the default setting for Margin and Padding was individual instead of "all". Because if padding-left is set to 50px and i edit the button to change only that setting, by default it will be applied to all (top, bottom and right also).

2) Although is interesting to have the freedom to set the unit i desire, it would be nicer if the default were (px), so if i add only the number 50 it automatically assumes it is 50px and applies the setting. And if i specify % or other, it will apply that setting.

--

Since is my first time communicating, let me just say: this page builder is awesome. Is the one that currently has the most potential, in my opinion (specially aiming for a simplified client-oriented front-end editing experience). Great work Andrew, congratulations and thanks for your support (in general, as i've been following Tailor-related issues around).

**Comment by andrew-worsfold** [comment] 2016-10-10 23:14
Thanks for raising this, @talesg (and for your kind words!).

The issue is that the live updates performed by JavaScript do not target the inner button element.  This causes the padding to appear like margin (and the discrepancy between the live updates and those from the server which arise from changing things like the label).

I have a fix for this available which will be released in the next version (1.6.1.).

Regarding your other points:

1) An assumption I made early on is that most people who were wanting to add/remove margin or padding on an element would be doing so evenly across all sides.  I think you may be right in that this is more of an advanced user feature and it's therefore likely they would be making refinements of the sort you mentioned.  I am happy to consider changing this default but would like to try and get feedback from some other users first regarding their usage of this setting.

2) That's a good idea.  I will look to include this in an upcoming version of Tailor!

Cheers,
Andrew.

**Comment by andrew-worsfold** [comment] 2016-10-14 03:50
Closing this issue as the bug has been resolved, however will look to include those recommendations in a future version of Tailor!

**Closed by andrew-worsfold** 2016-10-14 03:50 UTC
Labels: bug
